name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v1.0.0, v1.2.3

jobs:
  build-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller vendor_order_parser.spec

      - name: List files in workspace
        run: ls -R

      - name: Package release assets
        run: |
          New-Item -ItemType Directory -Path "release_package"
          Copy-Item -Path "dist/vendor_order_parser.exe" -Destination "release_package/"
          Get-ChildItem -Path "." -Filter "*.xlsx" | Copy-Item -Destination "release_package/"
          $asset_name = "vendor_order_parser-${{ github.ref_name }}.zip"
          Compress-Archive -Path "release_package/*" -DestinationPath $asset_name
          echo "ASSET_NAME=$asset_name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET_NAME }}
